stages:
    - build
    - test

build:
    tags:
        - ci
    stage: build
    script:
        - echo "Building application."

test-job1:
    tags:
        - ci
    stage: test
    script:
        - echo "This job tests something."

test-job2:
    tags:
        - ci
    stage: test
    script:
        - echo "Hello, $GITLAB_USER_LOGIN!"
        - echo "This job tests some other thing."

test-board:
    tags:
        - ci
    stage: test
    script:
        - echo "Board test running"
